import { readFile, writeFile } from 'node:fs/promises';
import process from 'node:process';
import postcss from 'postcss';
import prefixSelector from 'postcss-prefix-selector';
import { format, resolveConfig } from 'prettier';

const GENERATED_HEADER = `/*
 * Generated by scripts/build-styles.mjs. Do not edit directly.
 * Source: pdfjs-dist/web/pdf_viewer.css and src/styles/reader.css.
 */\n`;
const SCOPE_SELECTOR = '.abyss-documents';
const PDFJS_STYLES_PATH = 'node_modules/pdfjs-dist/web/pdf_viewer.css';
const READER_STYLES_PATH = 'src/styles/reader.css';
const OUTPUT_PATH = 'styles.css';

const [pdfjsStyles, readerStyles] = await Promise.all([
  readFile(PDFJS_STYLES_PATH, 'utf8'),
  readFile(READER_STYLES_PATH, 'utf8'),
]);
const prefixed = await postcss([
  prefixSelector({
    prefix: SCOPE_SELECTOR,
  }),
]).process(pdfjsStyles, { from: PDFJS_STYLES_PATH });
const prettierConfig = (await resolveConfig(OUTPUT_PATH)) ?? {};
const output = await format(
  `${GENERATED_HEADER}${prefixed.css.trimEnd()}\n\n${readerStyles.trim()}\n`,
  {
    ...prettierConfig,
    filepath: OUTPUT_PATH,
  },
);

assertScopedSelectors(output);

if (process.argv.includes('--check')) {
  const current = await readFile(OUTPUT_PATH, 'utf8').catch(() => '');
  if (current !== output) {
    throw new Error('styles.css is stale; run pnpm build:styles and commit the result.');
  }
} else {
  await writeFile(OUTPUT_PATH, output);
}

function assertScopedSelectors(css) {
  const root = postcss.parse(css);
  root.walkRules((rule) => {
    if (isKeyframeStep(rule)) return;
    for (const selector of rule.selectors) {
      if (!selector.trimStart().startsWith(SCOPE_SELECTOR)) {
        throw rule.error(`Unscoped selector: ${selector}`);
      }
    }
  });
}

function isKeyframeStep(rule) {
  let parent = rule.parent;
  while (parent) {
    if (parent.type === 'atrule' && /(?:^|-)keyframes$/i.test(parent.name)) return true;
    parent = parent.parent;
  }
  return false;
}
